import Head from "next/head";
import Header from "../components/Header/Header";

const Home = () => {
  return (
    <div className="py-3 px-6 mx-auto max-w-7xl">
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Header />
      </header>
      <main></main>

      <footer></footer>
    </div>
  );
};

export default Home;
