import Head from "next/head";
import HeroSection from "../components/HeroSection";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Iman Khorshidi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <HeroSection />
      </div>
      <footer></footer>
    </div>
  );
};

export default Home;
